apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:EBtsAc3wCQhYJK0HrFFat4KBW1OLaSQwFOAlWhAz8i63zY1V25x7quJV4y3R5QlnD+G/aGGAAKypWMezVORzp8NjRYXUBT/RnfjgNfHphqrQu8v69PF+IIHLtKhtK5ef2DfYs4Ehq7i9XFtOK8i18p/oePE=,iv:9bheTrfV7xIs9eskYi4CyMQivUgs+xeKezzFNVz6L3s=,tag:8ab5gbcH07GQBFy8xlOQbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-14T15:06:47Z"
    mac: ENC[AES256_GCM,data:Tj4003SCs9CY0DnNfY2KTYgT05aOcohNC3Nw+1d1I8+BQPeBlFQbwUPW6I9FLIPgVBSlx6rb3cmDEU2aiHD2EasXnoDaraUG0l3YbLxfq3RrQtN5fhJb0ZqC95nyPVvmptvgKf53lSeDStVZ9IMT8RJ0TFnGRUrGKYjMtQBdPpo=,iv:u3BBcUq9F/xa7Wy9HdQTFhEqXLSIk9GWZLuyvj6yczQ=,tag:iIwb7YwskZ/1Jht926xunw==,type:str]
    pgp:
        - created_at: "2022-03-14T15:06:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA6PfV/p0xRgkAQv+JGZUDOwWq4FFSdbo8bjZctvIdkUheZ6wMrpVit0RO6+Q
            242fO7vZs3pFOv1Agt4NL+KGI1i3VCoXD783VZVQ7uJLlKPj7MhvOJlBJnNPCLUp
            u4irJqZXsWEIY/KCRzz7vRA27GxppUxhx2Dq+1HMFE/iTFrN0J17ZvXflkb1EqqT
            437fakRP8wxCDcFl+MI97FEc6lyvVv8LSlH+obiwkq6aiELIZwax7zyGNtSl2okK
            Gi34vhmoOiRfAkRngFhTRxcx+BpPkV8uZTpSqCm5RseW1xn09CgwdIinxF7SP/O9
            VWLjVGA8u/+lzqmRgf6NdM44aC6VSp800gSzg5yvp5B5r7K9BqRfOJlb4hOLjdPQ
            P64OF4R8Az7UvryRM/oRXlp24XSm7QCFmVGLV+zCXxoYaCevbLlYzdovB+C5NZjB
            ZljqdJFOPkqGud0+RFuvrzKAZHVG4t09VYUzNHuQWnYpml6XkudyUPcdgzZTeeKC
            OX8wudYLRgLtKQA9/s7x0lwBMUnzxJZtp3TlfvEITURMhKVhf9voftiyIkCwXvzl
            WeYqz/ItK60taQ2fuztjhz8cuZL7Cn3+RHUXJ0FdamUbM4dz/MJ7gCpcCw3TFgja
            mg+9mUI2lvYrxGosgg==
            =Oh5J
            -----END PGP MESSAGE-----
          fp: E7F9E6D048D72E40827856BA1FA5A545202535FE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
