apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:f9oPVQPp2VMEvGOGw4gATzyudWMR9Qm40T+EVFyFJ7zmIecHRRVsBoxnz/eANMieVRL1OPL/NHVbUfxYpSBnN/sJfa2XKA4CRojI+0TQOLy7GYuO+VY/fLjjPAAFDUbZUpaDyPwUEuZ7rAOV38qkT2uXsNA=,iv:lifRJOfV91uPF7cXozkhlWeBKiNdAevbFDUOF8KDz90=,tag:/lhtfmRUWcpNqFgEdeQlhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-09T15:30:04Z"
    mac: ENC[AES256_GCM,data:4Vj/ofkTvrpOy2mhfBcRutDQ/wxEprEwwwdNHRHxJ5IKHzyQwCRMcUqlr9rh8OwfKczVdGDT2bphRZzQrrYK10eVxj7wcmJkX0te/WAcoNeDGz4R2WHwDgjDVej3MV/01I37j0mFQuE4VrqvzdMqMO4lYPK9dOzqDmSxUKhjq40=,iv:3m0FHyJQUmORLHgvgmxiOE89Swe8nog0eRLzeSOYCEk=,tag:98Mx+2THrc4hel0PF0G51Q==,type:str]
    pgp:
        - created_at: "2022-03-09T15:30:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3+EjISfTFC7AQ//Xk4KrD09sM3M/0C0HQ9gLm9w1i2ePZBpnHK/FNi0pRUV
            kg8y0h5GQE3/ZwgmB7q6+iMqQE9YuqHnIb5HVosfAinnUG+3XY7rtOm4w8C7JhfZ
            2v2RNgFYmEqvMePdOT/mcvOfZ9MaQbE4JkFtSWIplHdqNEUo7LPmU+bhGoQAAubC
            JlRAbnpn/OwZMgt1e4/S6ZLQhNra0qVheUJS7HSaaqa0AHq9ItEgsWiAXMzS6ZOS
            4pOwXCsplRqitFu63HekcxP71GQAfJ00Xveh22y5D0R5kMstbEUT9G7jr7vPZ7Zu
            uuvCHr1KEnX029ie8QhcA1sMI4d5gwsOjJqfFEY/UAWq8ifmivnd7QAJ2ORtz4ka
            S6kLNYH88+J2sh+xJPo2E0BjmCup5q2IBZXV4N2RM832XgxtJx5N0vJYwWFYBsxo
            QoydE6lxIbntt4SqODhU9CeKKsHtDSVrl28J7pG4WLQAaBU13gIClFnRryXw+2G1
            3FIEgmLwOyfcHIJu9sUjROU9Wiu8ZRCybjVHj+aZj+kUGHEx23ak/q5++lrxVQUO
            wly/HzrRET1ZnaC6l1VYJkRXTysB3LyHTZ7at7fF6R4s/8RV3AAxgExCY6KdpNnP
            hfH7OGu95lylqbS2cOEhFWdeuliEVuQ1yB/TddKcMKr09WsT+JSKhrjZqoJDIh/S
            XAGvvKYNJ0Lmv86GBk7GQXQYPqon+/qedGSxfHQ5SJM0Zk9mQTMmEROVA8OqYniM
            UNifFgygEYUjQPHeapm2pLomp9TIl/i0fVauPLMKawy0vgkO98u85RsIfTCT
            =tzr1
            -----END PGP MESSAGE-----
          fp: BEF8824916489C4BB02C4870C7DB760B7907C210
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
