name: Big Bang Test

on:
  push:
  workflow_dispatch:

jobs:
  deploy-rke2:
    runs-on: ubuntu-latest
    outputs:
      kvname: ${{ steps.deploy_rke2.outputs.kvname }}

    steps:
      - uses: actions/checkout@v2      
      - name: Deploy RKE2
        id: deploy_rke2
        run: echo "::set-output name=kvname::dsop-rke2-test-20-3ob"
   
  deploy-bigbang:
    runs-on: ubuntu-latest
    needs: deploy-rke2
    env:
      #TODO Need to update this
      KUBECONFIG: /home/runner/work/dsop-environment/dsop-environment/rke2.kubeconfig
    steps:
      - run: echo "hello"

  verify-reconciliation:
    runs-on: ubuntu-latest
    needs: deploy-bigbang
    env:
      #TODO Need to update this
      KUBECONFIG: /home/runner/work/dsop-environment/dsop-environment/rke2.kubeconfig
    steps:
      - name: Login to Azure US Gov Cloud with CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: 'AzureUSGovernment'
          enable-AzPSSession: false
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-verison: '3.x'
          cache: pip
      - run: pip install -r requirements.txt      
      - name: set kubeconfig
        env:
          KV_NAME: ${{ needs.deploy-rke2.outputs.kvname }}
        run: |          
          FILE=$(realpath rke2.kubeconfig)
          echo "Fetching kubeconfig from KeyVault $KV_NAME"
          az keyvault secret show --name kubeconfig --vault-name $KV_NAME -o json | jq -r '.value' > $FILE

          ls -la $FILE

          until kubectl version &> /dev/null
          do
            echo "Waiting for k8s server to respond..."
            sleep 10
          done
          
          kubectl version

      - name: Execute Pytest
        run: |
          
          until pytest -v tests/ &> /dev/null
          do
            echo "Waiting for reconciliation to complete..."
            kubectl get gitrepositories,ks,hr -A
            sleep 60
          done

          pytest -v tests/
